services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:8000"
        command: >
            bash -c "
              composer install &&
              php artisan migrate --force &&
              php artisan serve --host=0.0.0.0 --port=8000
            "
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
